version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    ports: 
#      - 51773
' new SuperServer Port
      - 1972
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
